"""added FoodEntry table

Revision ID: f53d4d1f70d5
Revises: 
Create Date: 2020-06-28 16:59:26.053772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f53d4d1f70d5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=240), nullable=True),
    sa.Column('meal_type', sa.String(length=20), nullable=True),
    sa.Column('consume_date', sa.Date(), nullable=True),
    sa.Column('entry_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('food_log')
    # ### end Alembic commands ###
